In [9]:
import pandas as pd
students = pd.read_json('datas/students_info.json')
students

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishingDate,Instructor,Location,TotalMarks
0,ST1001,Alif Rahman,Completed,2024-01-10,2024-04-25,Mr. Karim,Dhaka,258
1,ST1002,Fatima Akhter,In Progress,2024-02-05,None,Ms. Salma,Chattogram,184
2,ST1003,Imran Hossain,Completed,2024-02-18,2024-06-01,Mr. David,Rajshahi,247
3,ST1004,Jannatul Ferdous,Completed,2024-03-01,2024-07-10,Ms. Salma,Sylhet,251
4,ST1005,Kamal Uddin,In Progress,2024-04-15,None,Mr. Karim,Dhaka,192
5,ST1006,Laila Begum,Completed,2024-05-10,2024-09-12,Ms. Salma,Chattogram,243
6,ST1007,Mahmudul Hasan,Not Started,2024-07-20,None,Mr. David,Khulna,0
7,ST1008,Nadia Islam,Completed,2024-08-01,2024-11-28,Ms. Salma,Sylhet,267
8,ST1009,Omar Faruq,In Progress,2024-09-18,None,Mr. Karim,Rajshahi,210
9,ST1010,Priya Sharma,Completed,2024-10-05,2025-01-10,Ms. Salma,Dhaka,276

In [14]:
instructos_group = students.groupby("Instructor").count()
instructos_group

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishingDate,Location,TotalMarks
Instructor,,,,,,,
Mr. David,2,2,2,2,1,2,2
Mr. Karim,3,3,3,3,1,3,3
Ms. Salma,5,5,5,5,4,5,5